### ISSUE TITLE
LESS/SASS Based template?

### ISSUE THREAD

**Issue by Johns3n** [HTML24/HTML5-template#17]
With the importance of consistent/efficient code in the modern front-end world, why have you chosen not to base your front-end code core on either LESS/SASS? 

The benefits:
Leaner (and meaner) CSS.
More consistent CSS family trees.
Time saving with Mixins and Extends.

The cons:
Takes developers a little time to adjust to a new way of writing CSS.
(but we wen't through the same thing, when we went from table layout to div's)

**Comment by DKvistgaard** [comment]
LESS and SASS are awesome extensions of CSS and we do use them on different project. My personal favorite is SASS.

We don't however push our developers to use certain tools, and we love to have the freedom to choose the right language or tool for each specific project and working group.

This template is merely an empty template ready for everything. You can hereby take it and use SASS or LESS for the project. But it might be a good idea to supply a SASS and a LESS version of this template.

The last thing I really want to say here is that this template is for everyone to use. It's for the experienced developer who just want the bone structure instead of finding the CSS resets again, adding the right headers and so forth. It's also for the developers who've just started to look into the whole web developing world. So pushing these guys to use an extension to a language they might not even know yet, isn't (in our opinion) the best thing to do. Therefore we like to keep it as simple as possible.
