### ISSUE TITLE
Framework  / Grid in codebase

### ISSUE THREAD

**Issue by Johns3n** [HTML24/HTML5-template#19]
There are many benefits with using a framework or just a grids system.

The most prominent being that you get a certain code naming/writing convention, and more importantly. You keep widths out of your CSS (unless you run a silent grid system) and separate in a grid system file. 

This of course means that you as front-end developer can code more fast, and efficient as you do not have to worry about widths in your CSS and making it all align up nicely.

Now I know, that many client PSD files not necessarily always line up with a grid system and you if you are going for the 100% pixel correct implementation of PSD file, grids might not be for you! However 95% of the time I find that i can always adjust client PSD's to fit a grid system with little ekstra work.

This also means that other developers can quickly jump into other developers projects (in case of new job, sickness etc) with no problems (Especially if you follow the rules about BEM, OOCSS and SMACSS aswell) and not having to figure convoluted selectors and odd width definitions, that break apart if even 1 pixel is changed.

SOURCES:
http://t.co/z6nqrC4tRN <- one of the best vidoes about PSD to HTML,CSS
http://mashable.com/2013/04/26/css-boilerplates-frameworks/

**Comment by DKvistgaard** [comment]
Grid based templates are great and they do provide a lot great prestylings to make your work faster and easier.

This is however not the idea behind this template. As a wrote in one as comments to the other issues; this is an empty skeleton template that you can do with whatever you want. So if you want / need a grid for your template, then create one (it doesn't take that long when you know exactly how it should be for your project) or reuse one from a previous project.

If you like to use out-of-the-box-ready grid based templates with a lot of extra features, why not use [Bootstrap](http://getbootstrap.com/), [960 grid](http://960.gs/) or one of the many other available templates out there, instead of reinventing the wheel?
